version: "3"

services:
  adonis_example_web:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_PERSONAL_ACCESS_TOKEN=${GIT_PERSONAL_ACCESS_TOKEN}
    ports:
      - "3400:80"
    container_name: Abdel-FRONTENT-TEST-AUTOMATION
    environment:
      - USE_PRODUCTION = true
      - USE_PROD = true
      - USE_UAT = false
      - USE_STAGE = false
      - LOGIN_EMAIL_DEV=mattfeeqa@gmail.com
      - LOGIN_PASSWORD_DEV=Password10!
      - LOGIN_USERNAME_UAT=
      - LOGIN_EMAIL_UAT=mattfeeqa@gmail.com
      - LOGIN_PASSWORD_UAT=Password10!
      - LOGIN_USERNAME_PROD=${LOGIN_USERNAME_PROD}
      - LOGIN_EMAIL_PROD=mattfeeqa@gmail.com
      - LOGIN_PASSWORD _PROD=Password10!
      - ASPNETCORE_ENVIRONMENT=Staging
      - IdentitiesServiceURI=https://identities-service-sandbox-us.app.pplsicorp.com
      - DESIGN_SERVICE_URI=https://design.api.dev-legalshield.com
      - apiUUID=3a3d22ac-e7cc-11ea-adc1-0242ac120002
      - apiSecret=4a47c6de-e7cc-11ea-adc1-0242ac120002