version: '1.0'

stages:
  - 'quick'
  - 'regular'
  - 'complete'

steps:
  smoke-all:
    title: 'Smoke Test DEV'
    stage: 'regular'
    type: parallel
    steps:
      ls_smoke_dev:
        title: 'LegalShield'
        type: codefresh-run
        arguments:
          PIPELINE_ID: 65a6ba6467341dac3a405057
          ENABLE_NOTIFICATIONS: true
          VARIABLE:
            - PLAYWRIGHT_SUITE_TAG="@ls-smoke"
            - PLAYWRIGHT_ENV=""

      lsa_smoke_dev:
        title: 'LegalShield Associate'
        type: codefresh-run
        arguments:
          PIPELINE_ID: 65a6ba6467341dac3a405057
          ENABLE_NOTIFICATIONS: true
          VARIABLE:
            - PLAYWRIGHT_SUITE_TAG="@lsa-smoke"
            - PLAYWRIGHT_ENV=""

      sb_smoke_dev:
        title: 'Shield Benefits'
        type: codefresh-run
        arguments:
          PIPELINE_ID: 65a6ba6467341dac3a405057
          ENABLE_NOTIFICATIONS: true
          VARIABLE:
            - PLAYWRIGHT_SUITE_TAG="@shieldbenefits-smoke"
            - PLAYWRIGHT_ENV=""

      wals_smoke_dev:
        title: 'WALS'
        type: codefresh-run
        arguments:
          PIPELINE_ID: 65a6ba6467341dac3a405057
          ENABLE_NOTIFICATIONS: true
          VARIABLE:
            - PLAYWRIGHT_SUITE_TAG="@wals-smoke"
            - PLAYWRIGHT_ENV=""
