apiVersion: v1alpha
kind: playwright
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 15
  sauceignore: .sauceignore
playwright:
  version: 1.22.2
suites:
  - name: login
    testMatch: /login/login.spec.ts/
    mode: sauce
    platformName: macos 11.00
    params:
      browserName: chromium
      project: ''
rootDir: .
artifacts:
  download:
    match:
      - '*'
    when: pass
    directory: ./artifacts
