name: Test Action - Configurable Run
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests against'
        required: true
        default: 'main'
        type: string
      test_command:
        description: 'Full Playwright Run Command'
        required: true
        default: ''
        type: string

jobs:
  test-run:
    name: Test Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure npm for GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PATOKEN }}" > .npmrc
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        env:
          LOGIN_EMAIL_UAT: ${{ secrets.LOGIN_EMAIL_UAT }}
          LOGIN_PASSWORD_UAT: ${{ secrets.LOGIN_PASSWORD_UAT }}
          LOGIN_USERNAME_UAT: ${{ secrets.LOGIN_USERNAME_UAT }}
          LOGIN_EMAIL_QA: ${{ secrets.LOGIN_EMAIL_QA }}
          LOGIN_PASSWORD_QA: ${{ secrets.LOGIN_PASSWORD_QA }}
          LOGIN_USERNAME_QA: ${{ secrets.LOGIN_USERNAME_QA }}
        run: ${{ inputs.test_command }}
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results-${{ inputs.branch }}-${{ github.run_number }}
          path: test-results
          retention-days: 10
