name: LSUS Consumer Flow Suite - Hourly
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the top of the hour
  workflow_dispatch:
    inputs:
      run:
        description: 'Trigger the workflow via API. Set to "true" to run.'
        required: true
        default: 'false'

jobs:
  consumer-flow:
    name: Consumer Flow Regression
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure npm for GitHub Packages
        run: |
          echo "@legalshield:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PATOKEN }}" > .npmrc
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright Consumer Flow Regression tests
        env:
          LOGIN_EMAIL_UAT: ${{ secrets.LOGIN_EMAIL_UAT }}
          LOGIN_PASSWORD_UAT: ${{ secrets.LOGIN_PASSWORD_UAT }}
          LOGIN_USERNAME_UAT: ${{ secrets.LOGIN_USERNAME_UAT }}
        run: USE_UAT=true npx playwright test --grep @lsus-consumer-flow --workers 1 --retries 2
      - name: Upload consumer-flow-test-results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: consumer-flow-test-results
          path: test-results
          retention-days: 10
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PATOKEN }}
        with:
          report-path: './ctrf/*.json'
          summary-delta-report: true
          insights-report: true
          flaky-rate-report: true
          fail-rate-report: true
          slowest-report: true
          upload-artifact: true
        if: always()
      - name: Send Playwright Report to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: npx teams-ctrf results ctrf/ctrf-report.json --useAdaptiveCard --onFailOnly
        if: always()